baseURL: https://def4alt.github.io
title: def4alt
paginate: 5
theme: "PaperMod"
defaultContentLanguage: "en"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

taxonomies:
    category: "categories"
    tag: "tags"
    series: "series"

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
            category: categories
            tag: tags
            series: series
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5
                - name: Projects
                  url: projects
                  weight: 6
                - name: Tags
                  url: tags/
                  weight: 10
                - name: About
                  url: about
                  weight: 12

outputs:
    home:
        - HTML
        - RSS
        - JSON

assets:
    disableFingerprinting: true
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-touch-icon.png"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "My personal blog"
    author: Andrii Olkhovych

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    profileMode:
        enabled: false

    homeInfoParams:
        enabled: true
        Title: "Andrii Olkhovych"
        Content: >
            Programmer, student, **_unknown thinker_**

    socialIcons:
        - name: github
          url: "https://github.com/def4alt"
        - name: Email
          url: "mailto:the.def4alt@gmail.com"
        - name: Rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/def4alt/def4alt.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    googleAnalytics:
        disable: true
    vimeo:
        disable: false
        enableDNT: true
        simple: true
    twitter:
        disable: false
        enableDNT: true
        simple: true
    instagram:
        disable: false
        simple: true
    youtube:
        disable: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
