---
title: "What is the happiness of a person: recipes from Hryhorii Skovoroda"
date: 2019-12-14
draft: false
---

* У чому щастя людини: рецепти від Григорія Сковороди (English version below)

Для кожної людини щастя - це щось найприємніше. Саме ця приємність виділяє людину серед інших і кожна людина унікальна за набором цих приємностей. Григорій Сковорода вважав, що щастя людина відняйде тільки пізнавши Бога, пізнавши себе, а потім "сродню працю". Мабуть усі згодні із цим твердженням.

Сковорода вважав, що у людини є пекло та рай, які постійно протистоять одне з одному і тільки людина обирає, хто переможе. "I нiхто не може вбити в собi зло, коли не втямить спершу, що таке те зло, а що добро...", - мудрував він. В мене ж трохи інша думка: я вважаю, що пекло та рай - невід'ємні складові розуму. Вони не ворогують, а навпаки намагаються зустрітися. Але якщо людина закопує якусь частину у всесвіт тіней, людина перестає бути живою. Тобто, якщо людина побудує на дуже крихкій ділянці свого розуму міст між Реальністю та Фантазією та не зламає його, вона віднайде своє щастя. У більшості є три фази мосту: міст є, потім його нема, і знову він є. Завжди дуже прикро, що міст руйнується, бо на його відновлення потрібно багато кальцію та дендритів.

Григорій Савович вчив людей геоцентричній системі всесвіту організму, тобто серце - це те місце, де стався великий бум духовного перевороту. Саме там вперше запрацював духовний двигун. Він казав: "Без ядра горіх ніщо, як і людина без серця". Це не дивно, бо Григорій був з епохи Бароко, що була наступником епохи Ренесансу, де і жили ці ідеї. Але ми - "homo sapiens" з двадцять першого сторіччя знаємо, що серце не відповідає за духовний світ, цю роботу виконує мозок. Саме в цих завитках народжується наше пекло та рай. Ось так, наука знищила мабуть найромантичнішу теорію всесвіту Сковороди.

Але що таке "сродня праця"? "Хіба розумно чинить той, хто починаючи довгий шлях, в ході не дотримує міри?" - саме так міркував наш геоцентричник. На його думку найлегша й найприємніша праця є "сродньою". А ту, що є важкою і, на вашу думку непотрібною, слід оминати. Це і справді цікава і гарна філософія, як для мене - школяра. Але насправді визначити поняття "сродня праця" у загальному випадку для мене дуже важко. Може це і є пік ланцюга "Що таке щастя", який унікальний для кожного, а може є і вищі гори за Еверест.

Отже, для кожної людини щастя - це щось найприємніше. Саме ця приємність виділяє людину серед інших і кожна людина унікальна за набором цих приємностей. Григорій Сковорода вважав, що щастя - це пік Евересту, романтична система всесвіту людини та міст між пеклом та раєм, що постійно руйнується. Усі згодні із цим твердженням.

* What is the happiness of a person: recipes from Hryhorii Skovoroda

For every person, happiness is the most pleasant thing. It is this pleasure that distinguishes a person from others, and each person is unique in terms of a set of these pleasures. Hryhorii Skovoroda believed that a person will find happiness only after knowing God, knowing himself, and then "related work". Everyone agrees with this statement.

Skovoroda believed that a person has a hell and heaven, which are constantly opposed to each other, and only a person chooses who will win. "And no one can kill the evil in himself if he does not first find out what is evil and what is good...", he reasoned. I have a slightly different opinion: I believe that hell and heaven are inseparable components of the mind. They are not hostile, but on the contrary, they are trying to meet. But if a person buries some part in the universe of shadows, the person ceases to be alive. That is, if a person builds a bridge between Reality and Fantasy on a very fragile part of his mind and does not break it, he will find his happiness. Most have three phases of the bridge: there is a bridge, then it is gone, and then it is there again. It's always a shame that a bridge collapses because it takes a lot of calcium and dendrites to rebuild it.

Hryhorii Skovoroda taught people the geocentric system of the organism's universe, that is, the heart is the place where the great boom of the spiritual upheaval took place. It was there that the spiritual engine started working for the first time. He said: "A nut without a kernel is nothing, just like a person without a heart." This is not surprising, because Hryhorii was from the Baroque era, which was the successor of the Renaissance era, where these ideas lived. But we - "homo sapiens" from the twenty-first century know that the heart is not responsible for the spiritual world, this work is performed by the brain. It is in these curls that our hell and heaven are born. That's it, science has destroyed perhaps the most romantic theory of the Skovoroda universe.

But what is "related work"? "Is the one who, starting a long journey, does not keep his measure during the journey wise?" - this is exactly how our geocentric thought. In his opinion, the easiest and most pleasant work is "relative". And the difficult one and, in your opinion, unnecessary, should be bypassed. This is a really interesting and good philosophy, as for me - a schoolboy. But in fact, it is very difficult for me to define the concept of "related work" in general. Maybe this is the peak of the "What is happiness" chain, which is unique for everyone, or maybe there are higher mountains than Everest.

So, for every person, happiness is something most pleasant. It is this pleasure that distinguishes a person from others, and each person is unique in terms of a set of these pleasures. Hryhorii Skovoroda believed that happiness is the peak of Everest, a romantic system of the universe of man and the bridge between hell and paradise, which is constantly being destroyed. Everyone agrees with this statement.
